---
language: ruby
sudo: false
cache: bundler
before_install: rm Gemfile.lock || true
script:
  - bundle exec rake spec
notifications:
  email: false
rvm:
  - 2.0.0
  - 2.1.0
  - 1.9.3
  - 2.2.3
  - 2.4.0
env:
  # Note: Facter 3.x is CFacter, and not a gem
  matrix:
  - FACTER_GEM_VERSION="~> 2.5.0"
  - FACTER_GEM_VERSION="~> 1.7.0"
  - FACTER_GEM_VERSION="~> 2.0.0"
  - FACTER_GEM_VERSION="~> 2.1.0"
  - FACTER_GEM_VERSION="~> 2.2.0"
  - FACTER_GEM_VERSION="~> 2.3.0"
  - FACTER_GEM_VERSION="~> 2.4.0"

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.2.3
    - rvm: 2.4.0
    - env: FACTER_GEM_VERSION="~> 1.7.0"
    - env: FACTER_GEM_VERSION="~> 2.0.0"
    - env: FACTER_GEM_VERSION="~> 2.1.0"
    - env: FACTER_GEM_VERSION="~> 2.2.0"
    - env: FACTER_GEM_VERSION="~> 2.3.0"
    - env: FACTER_GEM_VERSION="~> 2.4.0"
